id: c63aecb41bfdfd6b7e1fac37c7cbe7bf
hardware_id: /vio_hardware/imu
sensor_type: IMU
sigmas:
  gyro_noise_density: 9.5813e-06
  gyro_bias_random_walk_noise_density: 0.000108400035241
  acc_noise_density: 0.00025217
  acc_bias_random_walk_noise_density: 0.000147
saturation_accel_max_mps2: 150.0
saturation_gyro_max_radps: 7.5
gravity_magnitude_mps2: 9.81
